name: Flutter app run
on:
  push:
    branches:
      - master
      - main
jobs:
  android-emulator-and-apk-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Flutter APp
        uses: actions/checkout@v4

      # - uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #     ssh-private-key: |
      #       ${{ secrets.SSH_PRIVATE_KEY }}
      #       ${{ secrets.SSH_PRIVATE_KEY_ALYF_PROV_PKG }}

      - name: Flutter Install
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            flutter clean
            flutter pub get
            flutter drive --driver=app-test/integration_driver/integration_test_driver.dart --target=app-test/tests/dummy_test.dart